### ISSUE TITLE
How to run the project.

### ISSUE THREAD

**Issue by linyu92** [crowsonkb/style_transfer#1]
So wonderful. Can it run at the demo image now ?

**Comment by crowsonkb** [comment]
I wrote up some installation instructions for OS X: https://github.com/crowsonkb/style_transfer/blob/master/README.md. Linux is similar but the locations of the Python 3.5 libraries will be distro-dependent.

**Comment by crowsonkb** [comment]
At this point I've written up [installation instructions for Linux](https://github.com/crowsonkb/style_transfer#building-pycaffe-for-python-35-ubuntu-1604), made it compatible with Python 2.7, and created [an Amazon EC2 image](https://github.com/crowsonkb/style_transfer/wiki/Cloud-computing-images).
