### ISSUE TITLE
Speed issues

### ISSUE THREAD

**Issue by ghost** [crowsonkb/style_transfer#14]
Style Transfer seems to iterate much slower than Neural Style on my machine. I'm using a GeForce 1060 and Neural Style will create a 256px image at about 5-10 iterations per second, but Style Transfer is more like 5 seconds each.

Is there any way around this? Thanks

**Comment by ghost** [comment]
Recompiling Caffe with MKL brought it down to about 1s per step/iteration.

**Comment by crowsonkb** [comment]
If it gets that much faster with Caffe using MKL, are you sure you're using the GPU? You have to specify --devices 0 (or something else not -1) as CPU is the default.

**Comment by crowsonkb** [comment]
On GPU most of the speed benefits are seen with a MKL-compiled Numpy and it is not fivefold.

**Comment by ghost** [comment]
Thanks! I didn't realize CPU was the default, --devices 0 did the trick. I could never get anything out of neural style on a CPU, so in reality it seems like style transfer is actually faster under at least some conditions.

Might I suggest....
-  Changing --devices to --gpu, seems to be standard for deep learning scripts
-  Putting it on the parameters page
