### ISSUE TITLE
Syntaxerror when running style_transfer.py

### ISSUE THREAD

**Issue by mtmarsh2** [crowsonkb/style_transfer#2]
Hi, I'm using Python3.4 and ran "python3 style_transfer.py -h" and got the error:

```
File "style_transfer.py", line 44
    gram = feat @ feat.T / np.float32(feat.size)
```

Specifically with the '@' symbol. Would this have something to do with me using 3.4 and not 3.5?

**Comment by crowsonkb** [comment]
Yes, @ for matrix multiplication was added in 3.5. I haven't tested it on
3.4 but you can replace that line with:

gram = feat.dot(feat.T) / np.float32(feat.size)

to see if there are any more issues with 3.4. There is one other matrix
multiplication that needs replacing.

**Comment by crowsonkb** [comment]
I replaced the matrix multiplications with their 3.4-compatible forms, but I still haven't tested it on 3.4.
