### ISSUE TITLE
ImportError: cannot import name 'CommandLineInterface'

### ISSUE THREAD

**Issue by Infinality** [crowsonkb/style_transfer#21]
Any ideas?  Thanks.

$ ./style_transfer.py 
Traceback (most recent call last):
  File "./style_transfer.py", line 35, in <module>
    import prompt
  File "/mnt/D/Work/style_transfer/prompt.py", line 7, in <module>
    from prompt_toolkit import CommandLineInterface
ImportError: cannot import name 'CommandLineInterface'

**Comment by crowsonkb** [comment]
Are you using prompt_toolkit 1.x? `style_transfer` doesn't work with 2.x yet.

**Comment by Infinality** [comment]
I was able to work around it by commenting out the reference to prompt.py.
