### ISSUE TITLE
What are the Style_Transfer equivalents of Neural-Style's -style_weight, -normalize_gradients, and -int image?

### ISSUE THREAD

**Issue by ProGamerGov** [crowsonkb/style_transfer#8]
What are the Style_Transfer equivalents of Neural-Style's -style_weight, -normalize_gradients, and -int image? I have been trying to convert settings that work well in Neural-Style, into the equivalent settings used by Style_Transfer, but I can't seem to find/figure out these last 3 commands.

**Comment by crowsonkb** [comment]
-style_weight: style_transfer always sets it to 1, and you have to scale the other weights accordingly.

-normalize_gradients: always enabled.

-init image: --init-image same_as_content_image.jpg

**Comment by ProGamerGov** [comment]
Thanks for the help!
